### ISSUE TITLE
Use Express middleware for JWT authentication to reduce code duplication

### ISSUE THREAD

**Issue by nt314p** [CSP02/ChatterBoxAPI#4]
Many routes begin with the following set of code that verifies the JWT token or sends an error:
```
if (!req.headers["authorization"]) return res.status(401).send({ error: types.ErrorTypes.NULL_TOKEN })
    const [scheme, token] = req.headers.authorization.split(" ")
    try {
        const decoded = jwt.verify(token, process.env.JWT_SECRET, { complete: true })
...
```
By using some authentication middleware that runs before authentication-protected routes, the above authentication code does not have to be repeated.

**Comment by CSP02** [comment]
oh I never know we can do something like that. Gonna implement it.

**Comment by CSP02** [comment]
Implemented middleware in latest commit.
